require:
  - standard
  - rubocop-rspec
  - rubocop-rake

inherit_gem:
  standard: config/base.yml

AllCops:
  NewCops: enable

RSpec/MultipleExpectations:
  Enabled: false

RSpec/ExampleLength:
  Max: 25
