source "https://rubygems.org"

gemspec

# debugging
gem "debug", ">= 1.0.0"
gem "pry"
gem "pry-byebug"

gem "rake"      # dev/test CLI, build system
gem "rspec"     # testing
gem "simplecov" # coverage
gem "standard"  # linting
