source "https://rubygems.org"

gemspec

ruby file: ".tool-versions"

group :development, :test do
  gem "rake", require: false

  gem "debug", ">= 1.0.0", require: false
  gem "pry", require: false
  gem "pry-byebug", require: false

  gem "standard", require: false
  gem "rubocop-rspec", require: false
  gem "rubocop-rake", require: false
  gem "rubocop-performance", require: false

  gem "yard", require: false
  gem "webrick", require: false
end

group :test do
  gem "rspec", require: false
  gem "rspec-benchmark", require: false
  gem "simplecov", require: false
end
