source "https://rubygems.org"

gemspec

group :development, :test do
  gem "rake", require: false

  gem "debug", ">= 1.0.0", require: false
  gem "pry", require: false
  gem "pry-byebug", require: false

  gem "standard", require: false

  gem "yard", require: false
  gem "webrick", require: false
end

group :test do
  gem "rspec", require: false
  gem "simplecov", require: false
end
