require "bundler/gem_tasks"

require "rspec/core/rake_task"
RSpec::Core::RakeTask.new(:spec)

require "rubocop/rake_task"
RuboCop::RakeTask.new

require "yard"
YARD::Rake::YardocTask.new do |t|
  t.stats_options = %w[--list-undoc]
end

desc "Run the documentation server"
task :doc do
  sh "bundle exec yard server --reload"
end

task default: %i[spec rubocop yard]
