name: Ruby
on:
  push:
    paths:
      - ruby/**
jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./ruby
    steps:
    - uses: actions/checkout@v4
    - uses: ruby/setup-ruby@v1
      with:
        # ruby-version: '3.4' # Not needed with a .ruby-version, .tool-versions or mise.toml
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
        working-directory: ./ruby
    - run: bundle exec rake
