name: Zig
on:
  push:
    paths:
      - zig/**
jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./zig
    steps:
    - uses: actions/checkout@v4

    - uses: mlugg/setup-zig@v2
      with:
        version: 0.14.1

    - run: zig build --summary all

    - run: zig build test --summary all

    - run: zig build docs --summary all
