name: Zig
on:
  push:
    paths:
      - zig/**
jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./zig
    steps:
    - uses: actions/checkout@v4
    - uses: mlugg/setup-zig@v1
      with:
        version: 0.13.0
    - run: zig build --summary all
    - run: zig build test --summary all
